#!/bin/bash

# Function to log messages
log_message() {
  echo "$(date +"%Y-%m-%d %H:%M:%S") - $1"
}

# Function to uninstall the Tenable Nessus Agent
uninstall_tenable_agent() {
  # Check if the script is run as root
  if [[ "$(/usr/bin/id -u)" -ne 0 ]]; then
    log_message "This script must be run as root. Exiting."
    exit 1
  fi

  # Find all of the Nessus Agent directories and files
  NESSUS_DIRS=$(find / -type d -name "NessusAgent" -o -type f -name "*nessusagent*")

  # Check and Remove all of the Nessus Agent directories and files
  if [[ ! -z "$NESSUS_DIRS" ]]; then
    rm -rf $NESSUS_DIRS
    log_message "Removed Nessus directories and files."
  else
    log_message "Nessus directories and files not found."
  fi

  # Disable the Nessus Agent service if it's running
  if launchctl list | grep -q com.tenablesecurity.nessusagent; then
    log_message "Disabling the Nessus Agent service..."
    launchctl remove com.tenablesecurity.nessusagent
    log_message "Disabled Nessus Agent service."
  fi

  log_message "Tenable Nessus Agent uninstallation process completed."
}

# Main execution starts here
log_message "Starting Tenable Nessus Agent uninstallation."
